version: "3.7"
services:
  api:
    image: comxmart-backend:latest
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongodb
    environment:
      - MONGO_URI="mongodb://127.0.0.1/27017/comxmart"
    networks:
      - network

    healthcheck:
      test: ["CMD", "nc", "-z", "mongodb", "27017"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - network

networks:
  network:
    driver: bridge
