version: "3.8"
services:
  api:
    image: easy-buy:latest
    container_name: easy-buy-api
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run dev
    depends_on:
      - mongodb
    networks:
      - network

    healthcheck:
      test: ["CMD", "nc", "-z", "mongodb", "27017"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  mongodb:
    image: mongo:latest
    container_name: easy-buy-db
    ports:
      - "27017:27017"
    networks:
      - network

networks:
  network:
    driver: bridge
