FROM node:18-alpine

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY package*.json ./

RUN npm ci

RUN npm install

COPY . .

RUN npm run build

COPY start.prod.sh ./

RUN chmod +x start.prod.sh

CMD ["./start.prod.sh"]