FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

RUN npm install

COPY . .

RUN npm run build

COPY start.dev.sh ./

RUN chmod +x start.dev.sh

# CMD ["./start.dev.sh"]
CMD ["node", "dist/app.js"]