name: backend-easy-buy

on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - #Checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v2

      - #Login to Docker Hub using secret in github
        name: Login to Docker hub
        uses: docker/login-action/@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - #Create env
        name: Create .env
        run: |
          touch .env
          echo ORIGIN=${{secrets.ORIGIN}} >> .env
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
          echo NODE_ENV=${{secrets.NODE_ENV}} >> .env
          echo PORT=${{secrets.PORT}} >> .env
          echo DB_HOST=${{secrets.DB_HOST}} >> .env
          echo DB_PORT=${{secrets.DB_PORT}} >> .env
          echo DB_NAME=${{secrets.DB_NAME}} >> .env
          echo CREDENTIALS=${{secrets.CREDENTIALS}} >> .env
          echo MONGO_INITDB_ROOT_USERNAME=${{secrets.MONGO_INITDB_ROOT_USERNAME}} >> .env
          echo MONGO_INITDB_ROOT_PASSWORD=${{secrets.MONGO_INITDB_ROOT_PASSWORD}} >> .env

      - #Create a build kit builder instance
        name: Set up docker Build
        uses: docker/setup-buildx-action@v2

      - #Build the container image and push it to Docker Hub with name backend-easy-buy
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/backend-easy-buy:latest

      - # Copy .env to VPS
        name: Copy .env to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: .env
          target: ./backend-easy-buy/.env

      - #Deploy To VPS
        name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VPS_IP}}
          username: ${{secrets.VPS_USERNAME}}
          password: ${{secrets.VPS_PASSWORD}}
          script: |
            cd backend-easy-buy
            curl -o docker-compose.prod.yml https://raw.githubusercontent.com/shirloin/backend-easy-buy/main/docker-compose.prod.yml
            curl -o start.prod.sh https://raw.githubusercontent.com/shirloin/backend-easy-buy/main/start.prod.sh
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/backend-easy-buy:latest
            docker compose -f docker-compose.prod.yml up -d
